version: "3.8"

services:
  frontend:
    build:
      context: ../CustomMenu-Frontend
    container_name: dev-frontend

    dns:
      - 8.8.8.8

    ports:
      - "5173:5173"

    volumes:
      - ../CustomMenu-Frontend:/app
      - /app/node_modules 

    working_dir: /app
    command: npm run dev

    networks:
      - devnet

networks:
  devnet:
