version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: devFrontend-menuMamaloo

    dns:
      - 8.8.8.8

    ports:
      - "5169:5173"


    volumes:
      - /home/mamaloomenu/devFrontend-menuMamaloo/github/CustomMenu-Frontend:/app
      - /app/node_modules

    working_dir: /app
    command: npm run dev

    env_file:
      - .env.dev


    networks:
      - swag_default

networks:
  swag_default:
    external: true